#Project Information
site_name: TSExplain
site_description: TSExplain is a Python library for interpretable time series classification.
site_author: Cedric Kulbach

theme:
  name: "material"

plugins:
- search
- autorefs
- mkdocstrings

#- mkdocs-jupyter

nav:
  - Home: index.md
  - Interpretability: InterpretabilityMethods.md
  - Models: Model_Interface.md
#  - Installation: installation.md
#  - Code Reference:
#      - Classification: classification.md
#      - Regression: regression.md
#      - Anomaly: anomaly.md
#  - Examples:
#      - Classification: examples/example_classification.ipynb
#      - Regression: examples/example_regression.ipynb
#      - Anomaly Detection: examples/example_ae.ipynb
#  - About: about.md