#Project Information
site_name: TSInterpret
site_description: TSInterpret is a Python library for interpretable time series classification.
site_author: Jacqueline Höllig
site_url: https://github.com/jhoelli/TSInterpret

# Repository
repo_name: TSInterpret
repo_url: https://github.com/jhoelli/TSInterpret
edit_uri: "https://github.com/jhoelli/TSInterpret"

copyright: Copyright &copy; 2019 - 2022

theme:
  name: "material"
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - def_list
  - footnotes
  - attr_list
  - md_in_html

plugins:
- search
- autorefs
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_style: google
          docstring_section_style: spacy
          show_source: False
          merge_init_into_class: True
- mkdocs-jupyter:
    execute: False
- bibtex:
      bib_file: "library.bib"



nav:
  - Home: index.md
  - Getting Started: GettingStarted.md
  - Interpretability: AlgorithmOverview.md
  - How-To:
    - Instance-Based Methods: 
      - Counterfactuals:
        - Ates: ./Notebooks/Ates_torch.ipynb
        - Nun-CF: ./Notebooks/NunCF_torch.ipynb
    - Feature Attribution Methods:
      - Leftist: ./Notebooks/Leftist_torch.ipynb
      - Saliency: ./Notebooks/Ismail_torch.ipynb
  - API References: 
    - Models: Model_Interface.md
    - InterpretabilityMethods: 
      - Counterfactual: ./Methods/CF.md
      - Saliency: ./Methods/Saliency.md
      - LEFTIST: ./Methods/Leftist.md