#Project Information
site_name: TSInterpret
site_description: TSInterpret is a Python library for interpretable time series classification.
site_author: Jacqueline Höllig

theme:
  name: "material"

plugins:
- search
- autorefs
- mkdocstrings
- mkdocs-jupyter
- bibtex:
      bib_file: "./docs/library.bib"
markdown_extensions:
  - footnotes

nav:
  - Home: index.md
  - Interpretability: InterpretabilityMethods.md
  - Usage:
    - Instance-Based Methods: 
      - Counterfactuals:
        - Ates: ./Notebooks/Ates_torch.ipynb
        - Nun-CF: ./Notebooks/NunCF_torch.ipynb
    - Feature Attribution Methods:
      - Leftist: ./Notebooks/Leftist_torch.ipynb
      - Saliency: ./Notebooks/Ismail_torch.ipynb
  - API References: 
    - Models: Model_Interface.md
    - InterpretabilityMethods: 
      - Counterfactual: ./Methods/CF.md
      - Saliency: ./Methods/Saliency.md
      - LEFTIST: ./Methods/Leftist.md
#  - Installation: installation.md
#  - Code Reference:
#      - Classification: classification.md
#      - Regression: regression.md
#      - Anomaly: anomaly.md
#  - Examples:
#      - Classification: examples/example_classification.ipynb
#      - Regression: examples/example_regression.ipynb
#      - Anomaly Detection: examples/example_ae.ipynb
#  - About: about.md